#!/bin/bash

# Show usage
if [ $# -lt 1 ]; then
  echo "Usage: $0 <data.csv>"
  exit 99
fi

PLOT_PATH="${1/.csv/}-plot.pdf"
BOXPLOT_PATH="${1/.csv/}-boxplot.pdf"

# PLOT DATA
# -- Ping over time
cat << EOF > /tmp/plot_ping.in
set datafile separator ","
set grid
set xlabel "Time [s]"
set ylabel "Ping (Round Trip) [ms]"
set title "Ping test to [$1]"

set style line 1 \
  linecolor rgb "red" \
  linetype 1 linewidth 1 \
  pointtype 1 pointsize 1.5

stats "$1" using 2:3 nooutput
min_x = STATS_min_x
max_x = STATS_max_x
min_y = STATS_min_y
max_y = STATS_max_y
diff_x = (max_x - min_x)
diff_y = (max_y - min_y)
mean_y = (STATS_mean_y)
median_y = (STATS_median_y)
set label 1 gprintf("min = %g", min_y) at diff_x*0.05, max_y
set label 2 gprintf("max = %g", max_y) at diff_x*0.05, max_y-(diff_y*0.05)
set label 3 gprintf("mean = %g", mean_y) at diff_x*0.05, max_y-(diff_y*0.10)
set label 4 gprintf("median= %g", median_y) at diff_x*0.05, max_y-(diff_y*0.15)

set xrange [0:max_x]
plot "$1" using 2:3 with linespoints linestyle 1 notitle

set term pdf
set output "$PLOT_PATH"
replot
EOF
gnuplot -persist /tmp/plot_ping.in
echo "Plot saved to [$PLOT_PATH]"

# -- Ping boxplot
cat << EOF > /tmp/plot_ping.in
set datafile separator ","
set xlabel "Time [s]"
set ylabel "Ping (Round Trip) [ms]"

set style fill solid 0.25 border -1
set style boxplot outliers pointtype 7
set style data boxplot
set xtics ('$1' 1,)
set title "Ping test to [$1]"

plot "$1" using (1):3 notitle

set term pdf
set output "$BOXPLOT_PATH"
replot
EOF
gnuplot -persist /tmp/plot_ping.in
echo "Plot saved to [$BOXPLOT_PATH]"
