# This cmake file configures the following cmake variables:
# - PROTO_FOUND
# - PROTO_INCLUDE_DIRS
# - PROTO_LIBRARIES

# Dependencies
FIND_PACKAGE(OpenCV REQUIRED)
FIND_PACKAGE(SuiteSparse REQUIRED)
FIND_PACKAGE(OpenMP REQUIRED)
FIND_PACKAGE(Eigen3 REQUIRED)

# Find proto
FIND_LIBRARY(PROTO_LIBRARY LIBRARY NAMES proto)

# Set PROTO_FOUND
IF(PROTO_LIBRARY)
  SET(PROTO_FOUND TRUE)
ELSE ()
  SET(PROTO_FOUND FALSE)
  MESSAGE(FATAL_ERROR "Failed to find libproto!")
ENDIF()

# Set PROTO_LIBRARIES
SET(PROTO_LIBRARIES
    ${OpenCV_LIBS}
    ${CERES_LIBRARIES}
    yaml-cpp
    proto)
SET(PROTO_INCLUDE_DIRS ${EIGEN3_INCLUDE_DIR})
