# This cmake file configures the following cmake variables:
# - PROTO_FOUND
# - PROTO_INCLUDE_DIRS
# - PROTO_LIBRARIES

# Dependencies
FIND_PACKAGE(OpenCV REQUIRED)
FIND_PACKAGE(SuiteSparse REQUIRED)
FIND_PACKAGE(OpenMP REQUIRED)
FIND_PACKAGE(Eigen3 REQUIRED)
INCLUDE_DIRECTORIES(${EIGEN3_INCLUDE_DIR})
FIND_PACKAGE(OpenMP REQUIRED)
if (OPENMP_FOUND)
  SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
  SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
endif()

# Find proto
FIND_LIBRARY(PROTO_LIBRARY LIBRARY NAMES proto)

# Set PROTO_FOUND
IF(PROTO_LIBRARY)
  SET(PROTO_FOUND TRUE)
ELSE ()
  SET(PROTO_FOUND FALSE)
  MESSAGE(FATAL_ERROR "Failed to find libproto!")
ENDIF()

# Set PROTO_LIBRARIES
SET(PROTO_DEPS
    ${OpenCV_LIBS}
    ${CERES_LIBRARIES}
    yaml-cpp
    apriltags
    pthread)
SET(PROTO_LIBRARIES ${PROTO_DEPS} proto)
SET(PROTO_INCLUDE_DIRS ${EIGEN3_INCLUDE_DIR})
