include ../config.mk

default: $(BLD_DIR)/test_core $(BLD_DIR)/test_factor

$(BLD_DIR)/test_atl: test_atl.cpp
	$(MAKE_TEST)

$(BLD_DIR)/test_calib: test_calib.cpp
	$(MAKE_TEST)

$(BLD_DIR)/test_core: test_core.cpp
	$(MAKE_TEST)

$(BLD_DIR)/test_dense: test_dense.cpp
	$(MAKE_TEST)

$(BLD_DIR)/test_euroc: test_euroc.cpp
	$(MAKE_TEST)

$(BLD_DIR)/test_factor: test_factor.cpp
	$(MAKE_TEST)

$(BLD_DIR)/test_frontend: test_frontend.cpp
	$(MAKE_TEST)

$(BLD_DIR)/test_kitti: test_kitti.cpp
	$(MAKE_TEST)
