#include "prototype/driver/camera.hpp"
#include "prototype/driver/i2c.hpp"
#include "prototype/driver/mpu6050.hpp"
#include "prototype/driver/pca9685.hpp"
#include "prototype/driver/sbgc.hpp"
#include "prototype/driver/uart.hpp"
