#include "prototype/driver/camera/camera.hpp"
#include "prototype/driver/gimbal/sbgc.hpp"
#include "prototype/driver/imu/mpu6050.hpp"
#include "prototype/driver/pwm/pca9685.hpp"
#include "prototype/driver/i2c.hpp"
#include "prototype/driver/uart.hpp"
